name: Unit Test

on:
  push:

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt

      - name: Unit test with Maven
        run: mvn --batch-mode --update-snapshots -e -V clean test
